### ISSUE TITLE
Arduino as controller

### ISSUE THREAD

**Issue by dceriman** [snhirsch/katana-midi-bridge#17]
Hi,
This is more question than issue :)
I want to build small controller as addition for GA-FC.
Installation of katana-midi-bridge on RPi was easy and straightforward. I use Pro Micro, it shows up in katana-midi-bridge as device.
Issue is if I can not send any midi message over USB. I used few midi libraries but still no luck.
Do you have some example that I can use as reference?
Is it even possible to use katana-midi-bridge like that or am i not understanding concept?
I am proficient with guitars and Arduino, but not that much with MIDI, to be honest. :)

Best regards from Serbia

**Comment by snhirsch** [comment]
For Arduino applications you should look in the Katana area of the VGuitar Forum: https://www.vguitarforums.com.  There are people there who work with the Arduino and could answer questions about it.  I know nothing about that platform.

**Comment by dceriman** [comment]
Thanks.
