### ISSUE TITLE
[OT] USB Audio Interface

### ISSUE THREAD

**Issue by Beanow** [snhirsch/katana-midi-bridge#2]
I'm sorry for going off topic here. But you are one of the very few people I could find that are working on Katana related things on linux. Have you been able to get the USB audio interface to work at all? The 3 MIDI endpoints seem to work well, but the audio interface is not looking as pretty for me.

1. The card shows up as 1x 4 channel duplex, 44.1khz, 32 bits.
While Windows gives 2x 2 channel duplex, 48khz 16/24 bits, i.e. the PRIMARY and SECONDARY stages in stereo.
1. Trying to send any audio to the device with aplay it will throw I/O errors on any channel.
1. Trying to connect it to jackq it will time out.

Have you run into any issues like this at all? Do you know of any people working on this?

The model I have is the 100W combo amp. ID `0582:01d8`.

```
$ time pasuspender -- aplay -v --dump-hw-params -fS32_LE -c4 -r44100 -d1 -Dhw:KATANA /dev/zero
Playing raw data '/dev/zero' : Signed 32 bit Little Endian, Rate 44100 Hz, Channels 4
HW Params of device "hw:KATANA":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S32_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 128
CHANNELS: 4
RATE: 44100
PERIOD_TIME: (136 743039)
PERIOD_SIZE: [6 32768]
PERIOD_BYTES: [96 524288]
PERIODS: [2 1024]
BUFFER_TIME: (272 1486078)
BUFFER_SIZE: [12 65536]
BUFFER_BYTES: [192 1048576]
TICK_TIME: ALL
--------------------
Hardware PCM card 1 'KATANA' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 4
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 32
  buffer_size  : 22050
  period_size  : 5513
  period_time  : 125011
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 5513
  period_event : 0
  start_threshold  : 22050
  stop_threshold   : 22050
  silence_threshold: 0
  silence_size : 0
  boundary     : 6206523236469964800
  appl_ptr     : 0
  hw_ptr       : 0
aplay: pcm_write:1940: write error: Input/output error

real    0m20.108s
user    0m0.012s
sys     0m0.000s
```

**Comment by snhirsch** [comment]
Hi!  I have never tried to use the audio interface.  My only interest in the amp is for live performance.

**Comment by Beanow** [comment]
Well I didn't expect to be looking into this on day one either. But I tried running the tone central in wine and it *must* be connected to MIDI 1 or MIDI 3 and the PRIMARY audio interface. Has the same issue on windows if you manually select a different audio interface. But I would actually like to use the audio interface at some point.

Anyway, after a bunch of debugging it appears to be a driver issue. So I'll file a bugreport against the drivers.

Since I plan to keep this as my main amp for a couple of years and would love to experiment with all sorts of schemes to control the amp. Please let me know if there's anything I can help with.

I'm not terribly well versed in the low level MIDI format (yet, would like to learn) or reverse engineering. But I do have general programming skills. For example I could reference your protocol documentation to extend the API. Or look at doing GA-FC like bindings with arbitrary midi controllers.

**Comment by snhirsch** [comment]
Does the problem appear to be with the Linux drivers or Roland's?  If the latter, I wouldn't waste your time writing up a bug report.  I've seen few vendors that even care about problems with VMs, much less a native layer like WINE.  Mostly, if it ain't Windows 7/10 on bare metal they don't want to know about it.

The Katana bridge is designed to be driven by arbitrary MIDI controllers, so not sure I follow your last paragraph.  

Lastly, it would be great if someone wanted to help add the MIDX-20 CC-->sysex mappings to this code, but I'd like to do a partial implementation first to set an architectural example.

**Comment by Beanow** [comment]
The Linux driver `snd-usb-audio`. There's no Roland driver for Linux that I've seen. And indeed I ran into statements before VMs are not officially supported for the Katanas. Which makes sense imo, neatly isolating USB devices and exclusively assigning them to a VM is a pain to do.

What I meant with the last paragraph was about binding individual parameters, rather than full presets. For example:

![Akai LPD 8](http://static.keymusic.com/products/110578/XL/akai-lpd8-laptop-pad-controller.jpg)

These pads could do stompbox like on/off toggling for the effects. Or change to Ch1-4 of the tone settings. And the knobs could be linked to individual parameters, like a delay feedback or the noise gate threshold. Which I assume is similar to what you meant with
> Make internal ("deep") parameters accessible through standard CC messages.


I don't have a MIDX-20 nor any 5-pin devices to test with. Running straight USB through a desktop/laptop. But I can have a look at architecture, internal data formats and whatnot.

**Comment by Beanow** [comment]
For reference, this is the bugreport https://bugzilla.kernel.org/show_bug.cgi?id=195223
