### ISSUE TITLE
USB sniffing setup

### ISSUE THREAD

**Issue by Beanow** [snhirsch/katana-midi-bridge#3]
Which setup have you used for sniffing the USB communication between tone studio and the Katana? I've tried using wiresharks usbpcap and usbsnoop on windows 7 and 10, none of which captures any data about the Katana for me.

**Comment by snhirsch** [comment]
Ooof.  Yes, not so simple.  Do you have any way to PM me?  I can fill you in on the details off line.

**Comment by Beanow** [comment]
Would suggest gitter of discord, but I see you use vguitar more. Waiting for account approval. Found your thread on the subject there. http://www.vguitarforums.com/smf/index.php?topic=19707.0

**Comment by Beanow** [comment]
I'm able to get some results with USBLyzer based on that thread.

> USBLyzer looks like the way to go.  Here's the basic procedure:
> 1. Set it to capture only 'URB Bulk or Interrupt Transfer' and start recording. 
> 2. Go through a specific set of adjustments on BTS (e.g. Volume to 0, then 100, etc.), keeping notes on what's been done. 
> 3. When a batch is complete, stop recording and filter out everything but outgoing data. 
> 4. Export to CSV format.
> 5. Post-process with a Perl script to remove and interpret USB/Midi event packet headers, leaving only the actual sysex command.
> 6. Correlate each command with the actions done in step 2
> 7. Repeat, rinse.
